# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Data Inquiries
email: tomm.venturini@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Data Inquiries is a Public Data Lab initiative to facilitate generative encounters between institutions teaching critical data literacy and civil society organizations working with data.
baseurl: "/DataInquiries" # the subpath of your site, e.g. /blog
url: "https://publicdatalab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
remote_theme: densitydesign/pdatalab

plugins:
  - jekyll-feed
  - jekyll-remote-theme

color: river

pages:
  - name: Public Data Lab
    logo: "https://publicdatalab.org/wp-content/uploads/2021/02/pdl-logo.png"
  - name: CNRS Center for Internet and Society
    logo: "https://cis.cnrs.fr/wp-content/uploads/2020/05/cnrscis.png"

author:
  - name: Public Data Lab
    logo: "https://publicdatalab.org/wp-content/uploads/2021/02/pdl-logo.png"
  - name: CNRS Center for Internet and Society
    logo: "https://cis.cnrs.fr/wp-content/uploads/2020/05/cnrscis.png"
  - name: King’s College London
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/King%27s_College_London_logo.svg/1280px-King%27s_College_London_logo.svg.png"
  - name: University of Amsterdam
    logo: "https://study-eu.s3.amazonaws.com/uploads/university/uva-university-of-amsterdam-533-logo.png"
  - name: DensityDesign Lab
    logo: "http://densitydesign.org/wp-content/themes/whiteasmilk/img/logo_density.svg"


participants:
  - name: Tommaso Venturini
  - name: Jonathan Gray


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
